Repository avelino/awesome-go, pull requests merged in 2018-02, with the labels that each got.

#1801 Add strftime
  README.md
Labels: pending-review

#1800 Submitting Gomason for consideration
  README.md
Labels: pending-review

#1797 Update README.md (add github.com/cep21/circuit)
  README.md
Labels: pending-review

#1793 Added term-quiz to the README
  README.md
Labels: need coverage, pending-submitter-response

#1804 Add go-deep
  README.md
Labels: pending-review

#1802 Add gocmd
  README.md
Labels: pending-review

#1788 Added kcli to devops tools
  README.md
Labels: needs links, pending-review, quality standard

#1792 Add Cameradar library
  README.md
Labels: pending-submitter-response

#1815 Update README.md
  README.md
Labels: pending-review

#1811 add pdfgen
  README.md
Labels: pending-review

#1807 Add go-prompt
  README.md
Labels: pending-review, pending-submitter-response, quality standard

#1796 Add commonregex library
  README.md
Labels: pending-review

#1817 Add GolangCI
  README.md
Labels: pending-review

#1820 add https://github.com/xujiajun/gorouter library
  README.md
Labels: pending-review

#1814 Add php-parser
  README.md
Labels: pending-review

#1821 TextRank package - Update README.md
  README.md
Labels: pending-review

#1824 Adding Heimdall HTTP client to the awesome list
  README.md
Labels: pending-review

#1827 Add go-server-timing
  README.md
Labels: pending-review

#1828 Add client-timing
  README.md
Labels: pending-review
