Repository avelino/awesome-go, pull requests merged in 2018-05, with the labels that each got.

#1908 adding InVisionApp/tabular library
  README.md
Labels: pending-review

#1912 add leandro-lugaresi/hub
  README.md
Labels: pending-review

#1906 add geoserver package
  README.md
Labels: pending-review

#1886 Add a go algorithms repo
  README.md
Labels: pending-review

#1918 Added Sydney AU meetup to readme
  README.md
Labels: pending-submitter-response

#1923 Add lstags
  README.md
Labels: pending-review

#1915 slowpoke - Key-value store with persistence
  README.md
Labels: pending-review

#1924 add c4go
  README.md
Labels: pending-review

#1932 Add lwc
  README.md
Labels: pending-review

#1929 ADD: Onelog to logging section
  README.md
Labels: pending-review

#1925 Add Cameron
  README.md
Labels: pending-review

#1941 Add kelseyhightower/envconfig to Configurations section
  README.md
Labels: pending-review

#1938 Add deque to README.md
  README.md
Labels: pending-review

#1937 add go-excel
  README.md
Labels: pending-review

#1948 Add https://github.com/fulldump/biff
  README.md
Labels: needs tests, pending-submitter-response

#1947 add another go-log
  README.md
Labels: pending-review

#1950 add Golang Meetup Hamburg to the list of Meetups
  README.md
Labels: pending-review

#1949 Add sgreben/flagvar
  README.md
Labels: pending-review

#1954 add gubrak
  README.md
Labels: pending-review

#1934 add godscache a.k.a. Go DS Cache
  README.md
Labels: pending-review

#1939 Add go-trylock
  README.md
Labels: pending-review

#1946 Adds mspm package name in DataStructure and Algorithm list.
  README.md
Labels: pending-review

#1958 Add clockwork
  README.md
Labels: pending-review

#1959 Add package gojsonq
  README.md
Labels: pending-review
