Repository avelino/awesome-go, pull requests merged in 2018-12, with the labels that each got.

#2244 Add Octillery
  README.md
Labels: pending-review

#2251 Remove https://github.com/mgutz/dat
  README.md
Labels: pending-review

#2262 Deprecate github.com/franela/goreq
  README.md
Labels: pending-review

#2263 Deprecate github/facebookgo/httpcontrol
  README.md
Labels: pending-review

#2264 Deprecate github.com/markbates/validate
  README.md
Labels: pending-review

#2265 Deprecate github.com/codehack/go-relax
  README.md
Labels: pending-review

#2266 Deprecate github.com/volatile/core
  README.md
Labels: pending-review

#2267 Deprecate github.com/imdario/medeina
  README.md
Labels: pending-review

#2268 Deprecate github.com/daryl/zeus
  README.md
Labels: pending-review

#2269 Deprecate github.com/mvdan/interfacer
  README.md
Labels: pending-review

#2270 Deprecate github.com/GoClipse/goclipse
  README.md
Labels: pending-review

#2273 Add gonum
  README.md
Labels: pending-review

#2271 Update validate
  README.md
Labels: pending-review

#2272 Update go-telegraph
  README.md
Labels: pending-review

#2252 Remove https://github.com/bmizerany/pat
  README.md
Labels: help wanted, removal

#2248 Koazee
  README.md
Labels: pending-review

#2283 End description with dot
  README.md
  repo_test.go
Labels: pending-review

#2281 Add gitea-github-migrator
  README.md
Labels: pending-review

#2286 Add nio
  README.md
Labels: pending-review

#2290 fixed install github_flavored_markdown package
  Dockerfile
Labels: awesome-go.com, bug

#2289 Secdl remove
  README.md
Labels: pending-submitter-response

#2288 Added gqlc "GraphQL Compiler"
  README.md
Labels: pending-review

#2285 Add gmqtt
  README.md
Labels: pending-review

#2294 Google Drive client is not a cli parser library
  README.md
Labels: pending-review

#2297 Remove gqlc
  README.md
Labels: pending-review

#2295 Increase response time and add mentioned badge
  CONTRIBUTING.md
Labels: pending-review

#2292 added mvn-golang into Package Management section
  README.md
Labels: pending-review

#2293 Add MIMESniffer
  README.md
Labels: pending-review
