Repository avelino/awesome-go, pull requests merged in 2019-10, with the labels that each got.

#2748 Add mennanov/limiters
  README.md
Labels: pending-submitter-response, quality standard

#2738 Added go-simple-mail
  README.md
Labels: pending-submitter-response, quality standard

#2753 Add rain
  README.md
Labels: pending-review

#2755 Add sreq
  README.md
Labels: pending-review

#2763 fix(gorgonia): repo URL has changed
  README.md
Labels: pending-submitter-response, quality standard, question

#2769 Remove frameworks flagged as unmaintained
  README.md
Labels: removal

#2765 Add Programming with Google Go Specialization
  README.md
Labels: pending-submitter-response

#2756 Add cel-go
  README.md
Labels: pending-review

#2772 Remove Gomail since it's unmaintained since 2016.
  README.md
Labels: removal

#2737 Add Parsyl's parquet reader/writer lib
  README.md
Labels: pending-review

#2776 Adds bitcask & bitraft to Database section
  README.md
Labels: pending-submitter-response, quality standard

#2779 add trial
  README.md
Labels: pending-review

#2778 add schema
  README.md
Labels: pending-review

#2775 add goribot
  README.md
Labels: pending-review

#2774 Add sqlf
  README.md
Labels: pending-review

#2707 Add maroto
  README.md
Labels: pending-submitter-response, quality standard

#2741 Add Allenxuxu/gev
  README.md
Labels: pending-submitter-response, quality standard

#2747 Add lastpass-go
  README.md
Labels: pending-submitter-response, quality standard

#2746 Add fxamacker/cbor
  README.md
Labels: pending-submitter-response, quality standard

#2781 Add wroge/wgs84
  README.md
Labels: pending-submitter-response

#2785 Update GopherCon Europe to Berlin
  README.md
Labels: pending-review

#2782 Add bucket to the database tools
  README.md
Labels: pending-submitter-response

#2784 Add jcli add a devops tool
  README.md
Labels: pending-submitter-response

#2789 Add vl-go api client.
  README.md
Labels: pending-review

#2790 Add eko/gocache
  README.md
Labels: pending-review

#2793 Added GoPlantUML to awesome-go
  README.md
Labels: pending-review

#2783 Add terraform-provider-openapi
  README.md
Labels: pending-submitter-response

#2795 Add SimonBaeumer/cmd go package
  README.md
Labels: pending-review

#2796 Add liftbridge to the Distributed Systems section
  README.md
Labels: pending-review

#2803 remove jwc
  README.md
Labels: pending-review
