Repository avelino/awesome-go, pull requests merged in 2019-09, with the labels that each got.

#2497 Added the mailgun-go library to the list.
  README.md
Labels: pending-review

#2632 Add emperror
  README.md
Labels: pending-review

#2637 Add genv
  README.md
Labels: pending-review

#2639 Add implementation of Python's module "textwrap"
  README.md
Labels: pending-review

#2662 Added go-sundheit - a service health checks lib to distributed systems section
  README.md
Labels: pending-submitter-response, quality standard

#2663 Added libgoffi, an adapter library for integrating libffi in a way that it looks like native Go functions
  README.md
Labels: pending-submitter-response, quality standard

#2714 gowp
  README.md
Labels: pending-submitter-response

#2704 Add croc
  README.md
Labels: pending-submitter-response

#2715 Add gnet to the networking section
  README.md
Labels: pending-review

#2720 add bigfile
  README.md
Labels: pending-submitter-response

#2716 Add rest-go
  README.md
Labels: pending-submitter-response

#2725 Add Kivik
  README.md
Labels: pending-submitter-response

#2710 Add Falcon And Straf
  README.md
Labels: pending-submitter-response

#2723 gofal
  README.md
Labels: pending-review

#2727 Added abstract file storage (file,scp,gs,s3,mem)
  README.md
Labels: pending-review

#2729 Add m-zajac/json2go
  README.md
Labels: pending-review

#2733 Add Golang Developer Job Board
  README.md
Labels: pending-review

#2705 Add dudeldu
  README.md
Labels: pending-submitter-response, quality standard

#2724 ginrpc
  README.md
Labels: pending-review

#2735 Adds adlio/schema
  README.md
Labels: pending-review

#2732 Add remember-go
  README.md
Labels: pending-review

#2728 Add go-jet. Type safe SQL Builder for Go with automatic scan to desired arbitrary object structure.
  README.md
Labels: pending-review

#2744 Add qmuntal/stateless
  README.md
Labels: pending-review

#2745 Add wI2L/jettison
  README.md
Labels: pending-submitter-response, quality standard
