Repository avelino/awesome-go, pull requests merged in 2019-11, with the labels that each got.

#2806 remove color
  README.md
Labels: pending-review

#2786 Add Coffer
  README.md
Labels: pending-submitter-response

#2770 Add flamingo framework
  README.md
Labels: pending-submitter-response

#2754 Add 1build - command line
  README.md
Labels: pending-submitter-response, quality standard

#2810 Add video/m3u8 library
  README.md
Labels: pending-submitter-response

#2828 Remove dead link to termtables, fix typo slash
  README.md
Labels: pending-review, removal

#2809 Added Mailchain to awesome-go
  README.md
Labels: pending-submitter-response

#2814 pieterclaerhout/go-james
  README.md
Labels: pending-submitter-response

#2816 pieterclaerhout/go-log
  README.md
Labels: pending-submitter-response

#2818 pieterclaerhout/go-xray
  README.md
Labels: pending-submitter-response

#2824 Add cronrange package in 'Date and Time' section
  README.md
Labels: pending-review

#2820 Add GoThanks
  README.md
Labels: pending-submitter-response
