Repository avelino/awesome-go, pull requests merged in 2019-04, with the labels that each got.

#2449 Add iwanbk/bcache.
  README.md
Labels: pending-review

#2405 add Oto
  README.md
Labels: pending-submitter-response, quality standard

#2450 Add commander
  README.md
Labels: pending-review

#2451 Add dotchain/dot
  README.md
Labels: pending-submitter-response

#2452 Add Free Gophers Pack
  README.md
Labels: pending-review

#2372 add miku/zek
  README.md
Labels: pending-review

#2403 Add github.com/pascaldekloe/metrics
  README.md
Labels: pending-review

#2385 add github.com/ghostiam/binstruct
  README.md
Labels: pending-review

#2393 Update E-Books
  README.md
Labels: pending-review

#2365 Add go project layout
  README.md
Labels: pending-review

#2402 Add beaver to messaging packages
  README.md
Labels: pending-review

#2455 flop
  README.md
Labels: pending-review

#2456 Add JeremyLoy/config
  README.md
Labels: pending-review

#2457 Add treap
  README.md
Labels: pending-review

#2391 Add errlog
  README.md
Labels: pending-review

#2458 add crunch
  README.md
Labels: pending-review

#2461 Add assocentity
  README.md
Labels: pending-review

#2464 Add osamingo/checkdigit lib
  README.md
Labels: pending-review

#2460 Add sslmgr
  README.md
Labels: pending-review

#2466 add https://github.com/blockloop/scan
  README.md
Labels: pending-review

#2467 Added gfile
  README.md
Labels: pending-review

#2462 Update torrent entry
  README.md
Labels: pending-review

#2469 added interpol / police
  README.md
Labels: pending-review

#2472 Add go-toml
  README.md
Labels: pending-review

#2468 Added failpoint
  README.md
Labels: pending-review

#2474 Add typ
  README.md
Labels: pending-submitter-response

#2477 khezen/avro
  README.md
Labels: pending-review

#2483 Adds ULID
  README.md
Labels: pending-review

#2425 Added a guide to Golang e-commerce
  README.md
Labels: not alphabetical, pending-submitter-response

#2490 Add resgate
  README.md
Labels: pending-review

#2485 Add goreadability
  README.md
Labels: pending-review

#2481 Added go-mod-outdated
  README.md
Labels: pending-review

#2415 Add STL library
  README.md
Labels: pending-review

#2487 Add srfrog's dict package
  README.md
Labels: pending-review

#2480 Added gomalshare package
  README.md
Labels: pending-review

#2488 Tripadvisor
  README.md
Labels: pending-review

#2493 Add riemann-relay to Server Applications
  README.md
Labels: pending-review

#2494 Add rollingwriter
  README.md
Labels: pending-review

#2486 Add go-elasticsearch
  README.md
Labels: pending-review
