Repository avelino/awesome-go, pull requests merged in 2019-12, with the labels that each got.

#2829 Add uTask in 'DevOps Tools' section
  README.md
Labels: pending-review

#2840 add posener/cmd
  README.md
Labels: pending-review

#2843 feat: adding beyond as a new utility
  README.md
Labels: pending-review

#2835 add gospin
  README.md
Labels: pending-review

#2844 add psampaz/slice
  README.md
Labels: pending-review

#2849 update gorse in ML section
  README.md
Labels: pending-review

#2836 Add gosocsvr
  README.md
Labels: pending-review

#2859 pipe doesn't exist anymore
  README.md
Labels: removal

#2842 Add cookiecutter-golang
  README.md
Labels: pending-review

#2858 add go-generate-password
  README.md
Labels: pending-review

#2852 add disksing/iter
  README.md
Labels: pending-review

#2851 add a link to tickgit
  README.md
Labels: pending-review

#2856 add goe-joe
  README.md
Labels: pending-review

#2855 Add queryparam package to readme.
  README.md
Labels: pending-review

#2850 Add fergusstrange/embedded-postgres
  README.md
Labels: pending-review

#2771 Add ecommerce section with flamingo commerce
  README.md
Labels: pending-submitter-response

#2860 add fixedwidth package
  README.md
Labels: pending-review

#2869 Added go-restful-api project
  README.md
Labels: pending-review

#2865 Add Dingo dependency injection
  README.md
Labels: pending-review

#2872 add dp project to miscellaneous
  README.md
Labels: pending-review

#2871 Added package tome to the utilities list
  README.md
Labels: pending-review

#2882 Update description of networking framework: gnet
  README.md
Labels: pending-review
