Repository avelino/awesome-go, pull requests merged in 2020-08, with the labels that each got.

#3185 add cristalhq/jwt
  README.md
Labels: pending-submitter-response, quality standard

#3184 add cristalhq/aconfig
  README.md
Labels: pending-submitter-response, quality standard

#3190 Add gosd
  README.md
Labels: pending-submitter-response, quality standard

#3186 Update main location and description of ttlcache
  README.md
Labels: pending-submitter-response, quality standard

#3192 Add nan.
  README.md
Labels: pending-submitter-response, quality standard

#3195 Add goimports-reviser
  README.md
Labels: needs docs, pending-submitter-response

#3200 add html-to-markdown
  README.md
Labels: pending-submitter-response, quality standard

#3205 Remove not found library
  README.md
Labels: pending-review

#3206 Add qiniu/qmgo
  README.md
Labels: pending-review

#3188 add go-quartz
  README.md
Labels: pending-review

#3199 Add "Better Go Playground" service
  README.md
Labels: pending-submitter-response, quality standard

#3208 Add Themis crypto library to Security
  README.md
Labels: pending-submitter-response, quality standard

#3179 Add scany to utilities section
  README.md
Labels: pending-submitter-response, quality standard

#3202 Add neilotoole/errgroup to Goroutines section
  README.md
Labels: not alphabetical, pending-submitter-response

#3180 Add Gebug
  README.md
Labels: needs docs, pending-submitter-response, quality standard

#3218 Add covergates - Self-hosted code coverage report review and management service
  README.md
Labels: not alphabetical, pending-submitter-response
