Repository avelino/awesome-go, pull requests merged in 2020-10, with the labels that each got.

#3231 Add GoAudio - Native Audio Processing Library
  README.md
Labels: needs docs, pending-submitter-response, stale

#3262 Add Lille Gophers to website list
  README.md
Labels: not alphabetical, pending-submitter-response

#3254 add bokwoon95/go-structured-query to SQL query builder
  README.md
Labels: pending-submitter-response, quality standard

#3252 add janiltonmaciel/statiks
  README.md
Labels: needs docs, pending-submitter-response

#3279 Update README.md
  README.md
Labels: pending-review

#3285 Remove gostore from list (abandoned)
  README.md
Labels: pending-review, removal

#3259 Add Dasel.
  README.md
Labels: pending-submitter-response, quality standard

#3290 Update link for limetext
  README.md
Labels: pending-review

#3287 added govader
  README.md
Labels: pending-submitter-response, quality standard

#3289 Add Guora
  README.md
Labels: pending-review

#3299 Add sonh/qs
  README.md
Labels: pending-review

#3294 Add protoxy
  README.md
Labels: needs docs, pending-submitter-response

#3298 Add tik
  README.md
Labels: needs docs, pending-submitter-response, quality standard

#3302 Add 'For the Love of Go' and 'Go Code Club'
  README.md
Labels: pending-review

#3307 Added the Go Formatter library to the Awesome list.
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#3310 Add Gatus
  README.md
Labels: pending-submitter-response, quality standard

#3324 Update dasel description and change category
  README.md
Labels: pending-submitter-response
