Repository avelino/awesome-go, pull requests merged in 2020-12, with the labels that each got.

#3306 Add sleet
  README.md
Labels: pending-submitter-response, quality standard

#3370 Add gnomock to testing frameworks list
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#3391 Improving readabilitiy
  README.md
Labels: stale

#3387 Add abbreviate
  README.md
Labels: stale
