Repository avelino/awesome-go, pull requests merged in 2020-11, with the labels that each got.

#3338 added go-countries
  README.md
Labels: pending-review

#3330 Add Belfast Gophers meetup
  README.md
Labels: not alphabetical

#3291 Add statsviz
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#3332 add go-hit
  README.md
Labels: pending-submitter-response, quality standard

#3337 Add fastme library
  README.md
Labels: pending-submitter-response, quality standard

#3342 add GoHooks
  README.md
Labels: pending-submitter-response, quality standard

#3315 Add go-aws-news
  README.md
Labels: pending-review

#3364 Remove golangci-lint reference (golangci.com out of service)
  README.md
Labels: pending-submitter-response

#3351 Add stop-and-go
  README.md
Labels: needs docs, pending-submitter-response, quality standard

#3362 add goctx
  README.md
Labels: pending-submitter-response, quality standard

#3311 Add simple-jwt-provider (https://github.com/leberKleber/simple-jwt-provider)
  README.md
Labels: pending-submitter-response, quality standard, stale
