Repository avelino/awesome-go, pull requests merged in 2020-04, with the labels that each got.

#3035 added argon2-hashing package
  README.md
Labels: not alphabetical, pending-submitter-response

#2939 Add prototype game library
  README.md
Labels: pending-review

#3030 Add WebAssembly category
  README.md
Labels: pending-review

#3031 add ccbrown/api-fu
  README.md
Labels: needs docs, pending-submitter-response, quality standard

#3032 Add logur library
  README.md
Labels: pending-submitter-response

#3048 add shoutrrr
  README.md
Labels: pending-submitter-response, quality standard

#3049 Add Pixie to performance sectionn
  README.md
Labels: needs links, pending-submitter-response

#3047 Add silk and nfdump modules
  README.md
Labels: pending-submitter-response, quality standard
