Repository avelino/awesome-go, pull requests merged in 2020-01, with the labels that each got.

#2841 Created new Dynamic DNS category, added existing projects and new pro…
  README.md
Labels: pending-review

#2847 randomforest library
  README.md
Labels: need coverage, pending-submitter-response

#2848 Add cleanenv configuration library
  README.md
Labels: pending-submitter-response, quality standard

#2863 Add Curitiba meetup
  README.md
Labels: not alphabetical, pending-submitter-response

#2868 add go-localize
  README.md
Labels: pending-review

#2873 Added "ptr" package to miscellaneous
  README.md
Labels: pending-review

#2874 Add Language Detection API Go client
  README.md
Labels: pending-review

#2886 Add tracedb to readme file
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#2881 gormt
  README.md
Labels: pending-review

#2887 add rel
  README.md
Labels: pending-review

#2889 Add go-ssm-config
  README.md
Labels: pending-review

#2892 Update description of ants
  README.md
Labels: pending-review

#2893 Add mgm
  README.md
Labels: pending-review

#2891 Add httpproxy
  README.md
Labels: pending-review

#2896 Add golines
  README.md
Labels: pending-submitter-response, quality standard

#2894 Add gosip, client library for SharePoint API
  README.md
Labels: pending-review

#2895 Add lucassscaravelli/ej
  README.md
Labels: pending-review

#2880 Add conexec package to Goroutines category
  README.md
Labels: pending-review

#2901 Add github.com/cabify/timex to Testing/Mocks
  README.md
Labels: pending-review

#2902 Update Fyne description to match new release info
  README.md
Labels: pending-review

#2908 add database bbolt
  README.md
Labels: pending-review

#2899 Add kyoo
  README.md
Labels: pending-review

#2903 Add Ami.
  README.md
Labels: pending-review

#2905 Add dathoangnd/gonet
  README.md
Labels: pending-review

#2907 Add JSend
  README.md
Labels: pending-review

#2911 add entry to databases
  README.md
Labels: pending-review

#2910 add go-finnhub
  README.md
Labels: pending-review

#2912 Add gostl
  README.md
Labels: pending-review

#2914 Add go-pdu
  README.md
Labels: pending-review

#2925 Add go-twitch-irc
  README.md
Labels: pending-review

#2898 Add github.com/PumpkinSeed/errors
  README.md
Labels: pending-review
