Repository avelino/awesome-go, pull requests merged in 2020-09, with the labels that each got.

#3238 add go-todo-backend-example
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#3230 Replace otto to goja
  README.md
Labels: pending-submitter-response

#3246 Fix link to original GORM repository
  README.md
Labels: pending-review

#3155 Add lesismal/arpc
  README.md
Labels: needs tests, pending-submitter-response, quality standard, stale
