Repository avelino/awesome-go, pull requests merged in 2021-04, with the labels that each got.

#3545 Add roumon
  README.md
Labels: needs links, pending-submitter-response, quality standard, stale

#3548 Add go-yapla
  README.md
Labels: stale

#3557 Add higgs
  README.md
Labels: pending-submitter-response, quality standard

#3570 Add echotron telegram bot library
  README.md
Labels: pending-submitter-response, quality standard

#3576 Added github.com/alexeyco/pig
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#3553 add godesim & gitaligned
  README.md
Labels: just one package, pending-submitter-response

#3579 Added GoTuna
  README.md
Labels: pending-submitter-response, quality standard
