Repository avelino/awesome-go, pull requests merged in 2021-02, with the labels that each got.

#3388 Added go-clip repo
  README.md
Labels: pending-submitter-response, quality standard, stale

#3439 add box-cli-maker
  README.md
Labels: need coverage, pending-submitter-response, quality standard, stale

#3460 README.md: add ddt lib
  README.md
Labels: stale

#3463 Add nject/npoint dependency injection frameworks
  README.md
Labels: stale

#3465 Add gonfig to configuration libs
  README.md
Labels: stale

#3467 Add github.com/go-kata/kinit
  README.md
Labels: stale

#3494 Add rebed
  README.md
Labels: pending-submitter-response, quality standard

#3493 Add appstore-sdk-go
  README.md
Labels: pending-submitter-response, quality standard

#3466 add maja42/goval
  README.md
Labels: pending-submitter-response, quality standard
