Repository avelino/awesome-go, pull requests merged in 2021-08, with the labels that each got.

#3662 add dtm
  README.md
Labels: need readme english, pending-submitter-response

#3685 Add muesli/termenv
  README.md
Labels: need coverage, pending-review, pending-submitter-response, quality standard

#3634 Add Easegress
  README.md
Labels: pending-submitter-response, quality standard

#3697 add sunary/sqlize
  README.md
Labels: pending-submitter-response, quality standard, need coverage

#3661 Add go-starter
  README.md
Labels: pending-submitter-response, quality standard

#3677 Add bafi to Awsome Go list
  README.md
Labels: stale

#3678 README: Add requests: HTTP requests for Gophers
  README.md
Labels: stale

#3676 Add Githooks
  README.md
Labels: pending-submitter-response, quality standard

#3700 add customizable HTTP client library - httpc
  README.md
Labels: pending-submitter-response, quality standard, need coverage
