Repository avelino/awesome-go, pull requests merged in 2021-11, with the labels that each got.

#3753 Add todocheck to awesome-go
  README.md
Labels: needs tests, pending-submitter-response, needs links, need coverage

#3826 add andygeiss/esp32-transpiler - transpile from go to Arduino code.
  README.md
Labels: stale

#3829 Add fsm package
  README.md
Labels: stale

#3830 Add xid library
  README.md
Labels: stale

#3855 add go-htpasswd
  README.md
Labels: stale

#3854 Updated README.md with tutorials
  README.md
Labels: stale

#3842 Add "is" testing framework
  README.md
Labels: stale

#3862 fix teleterm typo
  README.md
Labels: stale

#3835 github.com/dedalqq/omg.testingtools add packager
  README.md
Labels: stale

#3778 add: prisma client go orm
  README.md
Labels: pending-submitter-response, quality standard, needs links, need coverage

#3892 add bqwriter to the list of Third-Party APIs
  README.md
Labels: pending-submitter-response, quality standard
