Repository avelino/awesome-go, pull requests merged in 2021-07, with the labels that each got.

#3622 Add awesome-go-extra
  README.md
Labels: pending-submitter-response

#3636 Added hexdingest/execpool to the Goroutines category
  README.md
Labels: stale

#3654 add Balerter to the DevOps section
  README.md
Labels: pending-submitter-response, quality standard

#3641 Add zenity
  README.md
Labels: pending-submitter-response, quality standard, stale

#3652 Add Track Awesome List Badge
  README.md
Labels: stale

#3655 Update OpenCage URL
  README.md
Labels: stale
