Repository avelino/awesome-go, pull requests merged in 2021-05, with the labels that each got.

#3547 Add go-wildcard
  README.md
Labels: needs links, pending-submitter-response, quality standard, stale

#3587 added go-type
  README.md
Labels: stale

#3597 Added GoFlake
  README.md
Labels: pending-submitter-response, quality standard
