Repository avelino/awesome-go, pull requests merged in 2021-01, with the labels that each got.

#3420 Remove and update 4 repos
  README.md
Labels: pending-review

#3432 Add golang-templates/seed
  README.md
Labels: pending-review

#3406 Add https://github.com/nlpodyssey/spago
  README.md
Labels: pending-review, stale

#3424 added cronticker
  README.md
Labels: not-in-a-right-category, pending-submitter-response

#3418 Add go-email-validator
  README.md
Labels: pending-submitter-response, quality standard

#3419 Add Playwright
  README.md
Labels: pending-submitter-response, quality standard

#3414 Add REST client and `database/sql` driver for Azure Cosmos DB
  README.md
Labels: pending-submitter-response, quality standard, stale

#3401 Create Build Automation category and add taskflow
  README.md
Labels: not-in-a-right-category, pending-review, stale

#3430 Add webp-server
  README.md
Labels: pending-submitter-response, quality standard

#3413 add wajox/gobase
  README.md
Labels: need coverage, needs links, pending-submitter-response, stale

#3454 Add Cortex-Tenant to Server Applications
  README.md
Labels: need coverage, pending-review, pending-submitter-response
