Repository avelino/awesome-go, pull requests merged in 2021-06, with the labels that each got.

#3601 Add command-chain
  README.md
Labels: stale

#3604 Add go-project-layout
  README.md
Labels: stale

#3617 added otpgen
  README.md
Labels: markdown format, pending-submitter-response

#3612 Add go-swagger-ui
  README.md
Labels: pending-submitter-response, quality standard

#3602 Add hoofli
  README.md
Labels: need coverage, pending-submitter-response, quality standard

#3618 Added go-andotp
  README.md
Labels: stale

#3625 Add chanify.
  README.md
Labels: stale

#3627 Adding kelindar/bitmap
  README.md
Labels: stale
