Repository avelino/awesome-go, pull requests merged in 2021-09, with the labels that each got.

#3644 Add sched
  README.md
Labels: pending-submitter-response, quality standard, stale

#3692 Add m2cgen for transpiling ML models into Go code
  README.md
Labels: pending-submitter-response, stale

#3698 Add Scout
  README.md
Labels: pending-submitter-response, quality standard, stale

#3703 feat: add gophers artwork and learning go by example tutorial
  README.md
Labels: stale

#3706 Added ticker to Financial
  README.md
Labels: stale

#3707 Add OjG
  README.md
Labels: stale

#3711 add easytcp
  README.md
Labels: stale

#3704 Add gosamples.dev
  README.md
Labels: pending-submitter-response, needs links

#3736 Add go-req
  README.md
Labels: pending-submitter-response, quality standard

#3715 Add throttle library
  README.md
Labels: stale

#3718 Update README.md
  README.md
Labels: pending-submitter-response, quality standard, needs links

#3739 Add rookie-ninja/rk-boot under Web Frameworks
  README.md
Labels: pending-submitter-response, quality standard

#3728 Add go clean template
  README.md
Labels: question, pending-submitter-response, quality standard

#3720 adding sshman
  README.md
Labels: pending-submitter-response, quality standard
