Repository avelino/awesome-go, pull requests merged in 2021-03, with the labels that each got.

#3476 add blocky to other software
  README.md
Labels: pending-submitter-response, quality standard

#3480 add go-zero (https://github.com/tal-tech/go-zero)
  README.md
Labels: needs docs, pending-submitter-response, quality standard

#3484 Added "slack-bot"
  README.md
Labels: pending-submitter-response, quality standard

#3490 Add link to hare under Databases.
  README.md
Labels: pending-submitter-response, quality standard

#3500 added go ml benchmarks
  README.md
Labels: not alphabetical, pending-submitter-response

#3523 remove github.com/krig/go-sox
  README.md
Labels: pending-review, removal

#3524 remove github.com/tcolgate/mp3
  README.md
Labels: pending-review, removal

#3526 Add Confetti Framework
  README.md
Labels: stale

#3542 Add docker-go-mingw
  README.md
Labels: pending-submitter-response, question

#3536 add jfcg/yell: yet another minimalistic logging library
  README.md
Labels: pending-submitter-response, quality standard

#3497 Adding Tasks
  README.md
Labels: pending-submitter-response, quality standard, stale

#3540 Update README.md
  README.md
Labels: needs links, pending-submitter-response, quality standard
