Repository avelino/awesome-go, pull requests merged in 2021-12, with the labels that each got.

#3898 Add new bot builder - larry
  README.md
Labels: pending-submitter-response, quality standard

#3897 add crawley
  README.md
Labels: stale

#3906 add go-lark
  README.md
Labels: stale

#3893 add sqlhooks
  README.md
Labels: stale

#3870 HnH/di - DI container library
  README.md
Labels: pending-submitter-response, quality standard

#3896 added neo cowsay
  README.md
Labels: stale

#3941 feat: add lark sdk
  README.md
Labels: needs docs, pending-submitter-response

#3927 Update README.md
  README.md
Labels: needs tests, pending-submitter-response, needs links, need coverage
