Repository avelino/awesome-go, pull requests merged in 2022-02, with the labels that each got.

#3905 Add ChainJacking by Checkmarx
  README.md
Labels: pending-submitter-response, quality standard, needs links

#3987 feat(README): add go-dummy
  README.md
Labels: pending-submitter-response, quality standard, stale

#4022 Add Trybe's style guide
  README.md
Labels: pending-review

#4034 Add objwalker
  README.md
Labels: pending-submitter-response, quality standard

#4038 Add pagoda
  README.md
Labels: pending-review

#4040 Add stew
  README.md
Labels: pending-submitter-response, quality standard, needs links, need coverage

#3995 add Mailx library
  README.md
Labels: pending-review

#4046 Add clover to "Database" section
  README.md
Labels: pending-submitter-response, quality standard

#4053 add req
  README.md
Labels: pending-submitter-response, quality standard

#4061 add go-cleanhttp
  README.md
Labels: pending-submitter-response, needs links, need coverage
