Repository avelino/awesome-go, pull requests merged in 2022-01, with the labels that each got.

#3936 add prolog
  README.md
Labels: stale

#3937 Added telego
  README.md
Labels: stale

#3899 Add hashicorp / go-retryablehttp
  README.md
Labels: pending-submitter-response, quality standard

#3964 doc: add protoncheck
  README.md
Labels: pending-submitter-response, quality standard

#3869 add a new networking lib
  README.md
Labels: pending-submitter-response, quality standard, stale

#3914 add piper
  README.md
Labels: stale

#3916 Add Plik to the Other Software section
  README.md
Labels: pending-submitter-response

#3997 add rueidis
  README.md
Labels: pending-submitter-response, quality standard, need coverage

#3996 doc(readme): add go-pkg repository
  README.md
Labels: pending-submitter-response, quality standard, need readme english

#3985 Add github.com/rsjethani/secret to security
  README.md
Labels: pending-submitter-response, quality standard
