Repository avelino/awesome-go, pull requests merged in 2022-04, with the labels that each got.

#4113 added Golang CRUD tutorial
  README.md
Labels: not alphabetical, pending-submitter-response

#4054 Add sqlc in "SQL Query Builder" section
  README.md
Labels: pending-submitter-response, quality standard

#4109 Adding html5tag
  README.md
Labels: stale

#4121 Removing gen:
  README.md
Labels: removal, stale

#4125 Removing skiplist:
  README.md
Labels: removal, stale

#4126 Removing merkletree:
  README.md
Labels: removal, stale

#4135 Removing scribble:
  README.md
Labels: removal, stale

#4157 Add wait-for
  README.md
Labels: pending-submitter-response

#4158 Add fasapay-sdk-go package
  README.md
Labels: needs docs, pending-submitter-response

#4167 add fp-go to Functional packages
  README.md
Labels: needs docs, need coverage

#4162 Add golamb
  README.md
Labels: needs docs, pending-submitter-response

#4165 Add goven
  README.md
Labels: needs docs, pending-submitter-response

#4152 add nfigure
  README.md
Labels: pending-submitter-response, quality standard, stale

#4136 Add twharmon/slices
  README.md
Labels: pending-submitter-response, quality standard, need coverage, stale

#4145 Adding go18ds
  README.md
Labels: pending-submitter-response, stale

#4176 Add goradd maps.
  README.md
Labels: stale

#4142 Add dynago
  README.md
Labels: needs tests, pending-submitter-response, quality standard, needs links, stale
