Repository avelino/awesome-go, pull requests merged in 2022-07, with the labels that each got.

#4245 add goami2
  README.md
Labels: not alphabetical, pending-submitter-response, stale

#4285 Add go-zoox/fetch
  README.md
Labels: stale

#4293 Add: fullproxy repository to awesome-go
  README.md
Labels: stale

#4292 add crab-config-files-templating
  README.md
Labels: needs docs, pending-submitter-response, quality standard

#4325 adding marshmallow
  README.md
Labels: stale
