Repository avelino/awesome-go, pull requests merged in 2022-03, with the labels that each got.

#4073 adding github.com/samber/lo
  README.md
Labels: pending-submitter-response, quality standard, need coverage

#4085 Removing Mustache
  README.md
Labels: removal

#4084 Removing Kasia
  README.md
Labels: removal

#4093 Add Mantil to DevOps Tools
  README.md
Labels: pending-submitter-response, quality standard

#4102 Add validator
  README.md
Labels: pending-submitter-response, needs links

#4068 add cdule
  README.md
Labels: pending-submitter-response, quality standard

#4083 Removing hero
  README.md
Labels: removal

#4082 Removing gofpdf
  README.md
Labels: removal

#4079 Removing Amber
  README.md
Labels: removal

#4078 Removing Ace:
  README.md
Labels: removal

#4105 Removing Go-Mix:
  README.md
Labels: removal

#4107 Remove port-midi:
  README.md
Labels: removal
