Repository avelino/awesome-go, pull requests merged in 2023-04, with the labels that each got.

#4792 Add kazhuravlev/just
  README.md
Labels: pending-submitter-response, quality standard

#4818 @GoDiscussions
  README.md
Labels: not alphabetical, pending-submitter-response

#4820 Golang Weekly
  README.md
Labels: not alphabetical, pending-submitter-response

#4846 add Pulse web framework
  README.md
Labels: pending-submitter-response, need coverage

#4399 Add sqlgen
  README.md
Labels: needs links, stale

#4462 Add LibraDB and Chronos
  README.md
Labels: stale

#4496 Added vacuum to the Code Analysis tools
  README.md
Labels: pending-submitter-response, needs links
