Repository avelino/awesome-go, pull requests merged in 2023-10, with the labels that each got.

#4630 clickhouse-go client
  README.md
Labels: pending-submitter-response, need coverage

#4400 add iso9660
  README.md
Labels: quality standard

#4658 Add library for the crypto NOWPayments API
  README.md
Labels: pending-review

#5034 Unison
  README.md
Labels: needs tests, pending-submitter-response, need coverage

#5027 Add Fast-Shot
  README.md
Labels: pending-review

#5036 chore: add oapi-codegen
  README.md
Labels: pending-review
