Repository avelino/awesome-go, pull requests merged in 2024-08, with the labels that each got.

#4472 add net in networking
  README.md
Labels: stale

#5377 Update README.md
  README.md
Labels: quality standard

#4718 Mention luks.go - a library to manage LUKS encrypted partitions
  README.md
Labels: needs tests, pending-submitter-response, quality standard, needs links, need coverage

#5374 Added dft
  README.md
Labels: pending-submitter-response

#5138 Add goenum
  README.md
Labels: pending-submitter-response

#4576 Add lnd repository
  README.md
Labels: pending-submitter-response, needs links

#4526 add jwx
  README.md
Labels: pending-submitter-response, quality standard
