Repository avelino/awesome-go, pull requests merged in 2024-09, with the labels that each got.

#5214 add envite to the list
  README.md
Labels: needs links

#4914 feat: add Blockchain/gno
  README.md
Labels: pending-submitter-response

#4749 Add iWF
  README.md
Labels: pending-submitter-response, quality standard, need coverage

#5338 Add Go-Shelve
  README.md
Labels: pending-review

#4492 add go-hep
  README.md
Labels: pending-submitter-response, quality standard
