Repository avelino/awesome-go, pull requests merged in 2024-05, with the labels that each got.

#5283 add hvalid project
  README.md
Labels: pending-submitter-response, need coverage

#5115 Add go-astiav
  README.md
Labels: pending-submitter-response

#4468 add podinfo in go tools
  README.md
Labels: not alphabetical, pending-submitter-response, needs links, need coverage, not-in-a-right-category

#5006 add wescale
  README.md
Labels: pending-submitter-response, needs links
