Repository avelino/awesome-go, pull requests merged in 2024-12, with the labels that each got.

#5239 add Gulter for file uploads
  README.md
Labels: pending-submitter-response, needs links, need coverage

#5405 add envyaml package to config loader part
  README.md
Labels: pending-submitter-response

#5545 add package vadiminshakov/committer
  README.md
Labels: needs tests, pending-submitter-response, quality standard, need coverage
